BeautyAndThePet/Web/BeautyAndThePet.Web/Controllers/AdsController.cs
namespace BeautyAndThePet.Web.Controllers
{
    using System;
    using System.Threading.Tasks;

    using BeautyAndThePet.Data.Models;
    using BeautyAndThePet.Services.Data;
    using BeautyAndThePet.Web.ViewModels;
    using BeautyAndThePet.Web.ViewModels.Ads;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;

    public class AdsController : Controller
    {
        private readonly UserManager<ApplicationUser> userManager;
        private readonly IAdsService adsService;

        public AdsController(UserManager<ApplicationUser> userManager, IAdsService adsService)
        {
            this.userManager = userManager;
            this.adsService = adsService;
        }

        [Authorize]
        public IActionResult New(int id)
        {
            var user = this.User.Identity.Name;

            var adInput = new AdInputViewModel { ApplicationUser = user, SentOn = DateTime.UtcNow };

            return this.View(adInput);
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> New(AdInputViewModel input)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(input);
            }

            var user = await this.userManager.GetUserAsync(this.User);

            try
            {
                await this.adsService.CreateAsync(input, user.Id);
            }
            catch (Exception ex)
            {
                this.ModelState.AddModelError(string.Empty, ex.Message);

                return this.View(input);
            }

            this.TempData["Message"] = "Ad added successfully.";

            return this.RedirectToAction("MyPets","Pets");
        }

        [Authorize]
        public IActionResult All()
        {
            var allAds = new AdsListViewModel()
            {
                Ads = this.adsService.GetAll(),
            };

            return this.View(allAds);
        }
    }
}

BeautyAndThePet/Web/BeautyAndThePet.Web/Controllers/CausesController.cs
namespace BeautyAndThePet.Web.Controllers
{
    using System;
    using System.Globalization;
    using System.Threading.Tasks;

    using BeautyAndThePet.Data.Models;
    using BeautyAndThePet.Services.Data;
    using BeautyAndThePet.Web.ViewModels.Causes;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Hosting;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;

    public class CausesController : Controller
    {
        private readonly ICausesService causesService;
        private readonly UserManager<ApplicationUser> userManager;
        private readonly IWebHostEnvironment environment;

        public CausesController(ICausesService causesService, IWebHostEnvironment environment, UserManager<ApplicationUser> userManager)
        {
            this.causesService = causesService;
            this.userManager = userManager;
            this.environment = environment;
        }

        [Authorize]
        public async Task<IActionResult> Create()
        {
            var user = await this.userManager.GetUserAsync(this.User);

            var viewModel = new CreateCauseInputModel
            {
                Title = "Save the dolphins",
                Description = "The population of dophins is highly decreasing last couple of years...",
                Funds = 1_000_000,
                BankAccount = "ABC123ABC123",
                AccountOwner = "Johnny Walker",
                Creator = user.UserName,
                StartOfPeriod = DateTime.Parse("01.01.2021", CultureInfo.InvariantCulture),
                EndOfPeriod = DateTime.Parse("02.11.2021", CultureInfo.InvariantCulture),
            };

            return this.View(viewModel);
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Create(CreateCauseInputModel input)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(input);
            }

            var user = await this.userManager.GetUserAsync(this.User);

            try
            {
                await this.causesService.CreateAsync(input, user.Id, $"{this.environment.WebRootPath}/images");
            }
            catch (Exception ex)
            {
                this.ModelState.AddModelError(string.Empty, ex.Message);

                return this.View(input);
            }

            this.TempData["Message"] = "Cause added successfully.";

            return this.RedirectToAction("MyCauses");
        }

        [Authorize]
        public IActionResult All()
        {
            var allCausesViewModel = new AllCausesListViewModel()
            {
                AllCauses = this.causesService.GetAll(),
            };

            return this.View(allCausesViewModel);
        }

        [Authorize]
        public IActionResult ViewCauseInfo(int id)
        {
            var chosenCauseView = this.causesService.GetById<CauseViewModel>(id);

            return this.View(chosenCauseView);
        }

        [Authorize]
        public async Task<IActionResult> MyCauses()
        {
            var user = await this.userManager.GetUserAsync(this.User);

            var causesViewModel = new MyCausesListViewModel() { MyCauses = this.causesService.GetMyCauses(user.Id) };

            return this.View(causesViewModel);
        }

        [Authorize]
        public IActionResult Edit(int id)
        {
            var inputModel = this.causesService.GetById<EditCauseInputModel>(id);

            return this.View(inputModel);
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Edit(int id, EditCauseInputModel input)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(input);
            }

            await this.causesService.UpdateAsync(id, input);

            return this.RedirectToAction(nameof(this.ViewCauseInfo), new { id });
        }

        [Authorize]
        public async Task<IActionResult> Delete(int id)
        {

            await this.causesService.DeleteAsync(id);

            return this.RedirectToAction(nameof(this.MyCauses));
        }
    }
}

BeautyAndThePet/Web/BeautyAndThePet.Web/ViewComponents/SidebarViewComponent.cs
namespace BeautyAndThePet.Web.ViewComponents
{
    using System.Linq;

    using BeautyAndThePet.Data.Common.Repositories;
    using BeautyAndThePet.Data.Models;
    using BeautyAndThePet.Services.Mapping;
    using BeautyAndThePet.Web.ViewModels;
    using Microsoft.AspNetCore.Mvc;

    public class SidebarViewComponent : ViewComponent
    {
        private readonly IDeletableEntityRepository<Ad> adRepo;

        public SidebarViewComponent(IDeletableEntityRepository<Ad> adRepo)
        {
            this.adRepo = adRepo;
        }

        public IViewComponentResult Invoke()
        {
            var model = new SidebarViewModel
            {
                Ads = this.adRepo.All().OrderByDescending(x => x.CreatedOn).To<AdViewModel>().Take(5).ToList(),
            };

            return this.View(model);
        }
    }
}

BeautyAndThePet/Web/BeautyAndThePet.Web/Views/Shared/_Layout.cshtml
@using BeautyAndThePet.Common
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@this.ViewData["Title"] - @GlobalConstants.SystemName</title>
    <link href="~/js/popper.min.js" />
    <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" asp-append-version="true" />
    <link href="~/css/site.min.css" rel="stylesheet" asp-append-version="true" />
    <link href="~/lib/bootstrap/dist/css/style.css" rel="stylesheet" asp-append-version="true" />
    <script src="https://kit.fontawesome.com/d4fc857696.js" crossorigin="anonymous"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <i class="fas fa-paw h5"></i>
                <a class="navbar-brand font-italic font-heading h6" asp-area="" asp-controller="Home" asp-action="Index">Beauty&ThePet</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    @if (this.User.Identity.IsAuthenticated)
                    {
                        <ul class="navbar-nav flex-grow-1 font h5">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                            <li class="dropdown">
                                <button class="btn dropdown-toggle" type="button" id="dropdownmenu" data-toggle="dropdown">Pets</button>
                                <ul class="dropdown-menu text-center" aria-labelledby="dropdownmenu">
                                    <li><a asp-controller="Pets" asp-action="Create">New pet</a></li>
                                    <li><a asp-controller="Pets" asp-action="MyPets">My pets</a></li>
                                    <li><a asp-controller="Pets" asp-action="All">All pets</a></li>
                                </ul>
                            </li>
                            <li class="dropdown">
                                <button class="btn dropdown-toggle" type="button" id="dropdownmenu" data-toggle="dropdown">Causes</button>
                                <ul class="dropdown-menu text-center" aria-labelledby="dropdownmenu">
                                    <li><a asp-controller="Causes" asp-action="Create">New cause</a></li>
                                    <li><a asp-controller="Causes" asp-action="MyCauses">My causes</a></li>
                                    <li><a asp-controller="Causes" asp-action="All">All causes</a></li>
                                </ul>
                            </li>
                            <li class="dropdown">
                                <button class="btn dropdown-toggle" type="button" id="dropdownmenu" data-toggle="dropdown">Chat</button>
                                <ul class="dropdown-menu text-center" aria-labelledby="dropdownmenu">
                                    <li><a asp-area="" asp-controller="Home" asp-action="Chat">Common chat</a></li>
                                </ul>
                            </li>
                            <li class="dropdown">
                                <button class="btn dropdown-toggle" type="button" id="dropdownmenu" data-toggle="dropdown">Ads</button>
                                <ul class="dropdown-menu text-center" aria-labelledby="dropdownmenu">
                                    <li><a asp-controller="Ads" asp-action="New">New message</a></li>
                                    <li><a asp-controller="Ads" asp-action="All">All messages</a></li>
                                </ul>
                            </li>
                            <li><partial name="_SearchUserPartial" /></li>
                        </ul>
                    }
                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">

            @if ((string)this.ViewData["Title"] == "Home Page" || !this.User.Identity.IsAuthenticated)
            {
                @this.RenderBody()
            }
            else
            {
                <div class="row">
                    <div class="col-md-9">
                        @RenderBody()
                    </div>
                    <vc:sidebar></vc:sidebar>
                </div>
            }
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; @DateTime.Now.Year - @GlobalConstants.SystemName - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js" asp-append-version="true"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js" asp-append-version="true"></script>
    <script src="~/lib/jquery-validation-unobtrusive/dist/jquery.validate.unobtrusive.js" asp-append-version="true"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js" asp-append-version="true"></script>
    <script src="~/lib/signalr/dist/browser/signalr.min.js" asp-append-version="true"></script>
    <script src="~/js/site.min.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

BeautyAndThePet/Web/BeautyAndThePet.Web/Views/Shared/_SearchUserPartial.cshtml
@if (this.User.Identity.IsAuthenticated)
{
    <div class="dropdown">
        <input type="text" class="dropbtn" placeholder="    Search user ..."  id="myInput" onkeyup="filterFunction()" onkeydown="filterFunction()">
        <div id="myDropdown" class="dropdown-content">
        </div>
    </div>
}