BeautyAndThePet/Web/BeautyAndThePet.Web/Controllers/MessagesController.cs
namespace BeautyAndThePet.Web.Controllers
{
    using System;
    using System.Threading.Tasks;

    using BeautyAndThePet.Data.Models;
    using BeautyAndThePet.Services.Data;
    using BeautyAndThePet.Web.ViewModels.Messages;
    using BeautyAndThePet.Web.ViewModels.Pets;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;

    public class MessagesController : Controller
    {
        private readonly IPetsService petsService;
        private readonly UserManager<ApplicationUser> userManager;
        private readonly IMessagesService messagesService;

        public MessagesController(IPetsService petsService, UserManager<ApplicationUser> userManager, IMessagesService messagesService)
        {
            this.petsService = petsService;
            this.userManager = userManager;
            this.messagesService = messagesService;
        }

        [Authorize]
        public IActionResult New(int id)
        {
            var pet = this.petsService.GetById<PetViewModel>(id);

            var petOwner = pet.OwnerUserName;
            var user = this.User.Identity.Name;

            var messageInput = new MessageInputViewModel { From = user, To = petOwner, SentOn = DateTime.UtcNow };

            return this.View(messageInput);
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> New(int id, MessageInputViewModel input)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(input);
            }

            var pet = this.petsService.GetById<PetViewModel>(id);

            var owner = await this.userManager.FindByIdAsync(pet.OwnerId);
            var user = await this.userManager.GetUserAsync(this.User);

            await this.messagesService.CreateSentMessageAsync(input, user.Id, owner.UserName);
            await this.messagesService.CreateReceivedMessageAsync(input, user.UserName, pet.OwnerId);

            return this.Redirect("/Pets/MyPets");
        }

        [Authorize]
        public async Task<IActionResult> Received()
        {
            var user = await this.userManager.GetUserAsync(this.User);

            var receivedMessagesViewModel = new MessagesListViewModel() { Messages = this.messagesService.GetReceivedMessages(user.Id) };

            return this.View(receivedMessagesViewModel);
        }

        [Authorize]
        public async Task<IActionResult> Sent()
        {
            var user = await this.userManager.GetUserAsync(this.User);

            var sentMessagesViewModel = new MessagesListViewModel() { Messages = this.messagesService.GetSentMessages(user.Id) };

            return this.View(sentMessagesViewModel);
        }

        [Authorize]
        public async Task<IActionResult> Unread()
        {
            var user = await this.userManager.GetUserAsync(this.User);

            var unreadMessagesViewModel = new MessagesListViewModel() { Messages = this.messagesService.GetUnreadMessages(user.Id) };

            return this.View(unreadMessagesViewModel);
        }

        [Authorize]
        public async Task<IActionResult> ReadSentMessage(int id)
        {
            var user = await this.userManager.GetUserAsync(this.User);

            var messageViewModel = this.messagesService.GetSingleSentMessage(id, user.Id);

            return this.View(messageViewModel);
        }

        [Authorize]
        public async Task<IActionResult> ReadReceivedMessage(int id)
        {
            var user = await this.userManager.GetUserAsync(this.User);

            var messageViewModel = this.messagesService.GetSingleReceivedMessage(id, user.Id);

            var correctMessage = messageViewModel.Result;

            return this.View(correctMessage);
        }

        [Authorize]
        public async Task<IActionResult> NewEmpty(string to)
        {
            var user = await this.userManager.GetUserAsync(this.User);

            if (to != null)
            {
                var messageInput = new MessageInputViewModel { From = user.UserName, To = to, SentOn = DateTime.UtcNow };

                return this.View(messageInput);
            }
            else
            {
                var messageInput = new MessageInputViewModel { From = user.UserName, SentOn = DateTime.UtcNow };

                return this.View(messageInput);
            }
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> NewEmpty(MessageInputViewModel input)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(input);
            }

            var user = await this.userManager.GetUserAsync(this.User);

            var receiverName = input.To;
            var receiver = await this.userManager.FindByNameAsync(receiverName);

            await this.messagesService.CreateSentMessageAsync(input, user.Id, receiverName);
            await this.messagesService.CreateReceivedMessageAsync(input, user.UserName, receiver.Id);

            return this.Redirect("/Messages/Sent");
        }
    }
}

BeautyAndThePet/Web/BeautyAndThePet.Web/Controllers/PetsController.cs
namespace BeautyAndThePet.Web.Controllers
{
    using System;
    using System.Globalization;
    using System.Text;
    using System.Threading.Tasks;

    using BeautyAndThePet.Data.Models;
    using BeautyAndThePet.Data.Models.Enumerations;
    using BeautyAndThePet.Services.Data;
    using BeautyAndThePet.Services.Messaging;
    using BeautyAndThePet.Web.ViewModels.Pets;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Hosting;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;

    public class PetsController : Controller
    {
        private readonly IPetsService petsService;
        private readonly IBreedsService breedsService;
        private readonly UserManager<ApplicationUser> userManager;
        private readonly IEmailSender emailSender;
        private readonly IWebHostEnvironment environment;

        public PetsController(IPetsService petsService, IBreedsService breedsService, 
            IWebHostEnvironment environment, UserManager<ApplicationUser> userManager, IEmailSender emailSender)
        {
            this.petsService = petsService;
            this.breedsService = breedsService;
            this.userManager = userManager;
            this.environment = environment;
            this.emailSender = emailSender;
        }

        [Authorize]
        public IActionResult Create()
        {
            var breeds = this.breedsService.GetAll<BreedDropDownViewModel>();

            var viewModel = new CreatePetInputModel
            {
                Name = "Kapitan Salam",
                Sex = Sex.Male,
                TypeOfPet = TypeOfPet.Dog,
                Breeds = breeds,
                BirthDate = DateTime.Parse("01.01.2021", CultureInfo.InvariantCulture),
                Description = "Very Aggressive",
                StartOfPeriod = DateTime.Parse("01.01.2021", CultureInfo.InvariantCulture),
                EndOfPeriod = DateTime.Parse("02.01.2021", CultureInfo.InvariantCulture),
            };

            return this.View(viewModel);
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Create(CreatePetInputModel input)
        {
            if (!this.ModelState.IsValid)
            {
                var breeds = this.breedsService.GetAll<BreedDropDownViewModel>();
                input.Breeds = breeds;

                return this.View(input);
            }

            var user = await this.userManager.GetUserAsync(this.User);

            try
            {
                await this.petsService.CreateAsync(input, user.Id, $"{this.environment.WebRootPath}/images");
            }
            catch (Exception ex)
            {
                this.ModelState.AddModelError(string.Empty, ex.Message);
                input.Breeds = this.breedsService.GetAll<BreedDropDownViewModel>();

                return this.View(input);
            }

            this.TempData["Message"] = "Pet added successfully.";

            return this.RedirectToAction("MyPets");
        }

        [Authorize]
        public IActionResult Edit(int id)
        {
            var breeds = this.breedsService.GetAll<BreedDropDownViewModel>();

            var inputModel = this.petsService.GetById<EditPetInputModel>(id);
            inputModel.Breeds = breeds;

            return this.View(inputModel);
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Edit(int id, EditPetInputModel input)
        {
            if (!this.ModelState.IsValid)
            {
                var breeds = this.breedsService.GetAll<BreedDropDownViewModel>();
                input.Breeds = breeds;
                return this.View(input);
            }

            await this.petsService.UpdateAsync(id, input);

            return this.RedirectToAction(nameof(this.ViewPetInfo), new { id });
        }

        [Authorize]
        public async Task<IActionResult> MyPets()
        {
            var user = await this.userManager.GetUserAsync(this.User);

            var petsViewModel = new MyPetsListViewModel() { MyPets = this.petsService.GetMyPets(user.Id) };

            return this.View(petsViewModel);
        }

        [Authorize]
        public IActionResult All(int id = 1)
        {
            const int PetsPerPage = 10;

            var allPetsViewModel = new AllPetsListViewModel()
            {
                Page = id,
                PetsCount = this.petsService.GetCount(),
                PetsPerPage = PetsPerPage,
                AllPets = this.petsService.GetAll(id, PetsPerPage),
            };

            return this.View(allPetsViewModel);
        }

        [Authorize]
        public async Task<IActionResult> MatchedPets(int id)
        {
            var user = await this.userManager.GetUserAsync(this.User);

            var pet = this.petsService.GetById<PetViewModel>(id);

            var matchedPetsViewModel = new MatchedPetsListViewModel()
            {
               MatchedPets = this.petsService.GetMatchedPets(pet.Id, user.Id),
            };

            return this.View(matchedPetsViewModel);
        }

        [Authorize]
        public IActionResult ViewPetInfo(int id)
        {
            var chosenPetView = this.petsService.GetById<PetViewModel>(id);

            return this.View(chosenPetView);
        }

        [Authorize]
        public async Task<IActionResult> Delete(int id)
        {
            await this.petsService.DeleteAsync(id);

            return this.RedirectToAction(nameof(this.MyPets));
        }

        [Authorize]
        public IActionResult AllMaleDogs(int id = 1)
        {
            const int PetsPerPage = 10;

            var allPetsViewModel = new AllPetsListViewModel()
            {
                Page = id,
                PetsCount = this.petsService.GetCount(),
                PetsPerPage = PetsPerPage,
                AllPets = this.petsService.GetAllMaleDogs(id, PetsPerPage),
            };

            return this.View(allPetsViewModel);
        }

        [Authorize]
        public IActionResult AllFemaleDogs(int id = 1)
        {
            const int PetsPerPage = 10;

            var allPetsViewModel = new AllPetsListViewModel()
            {
                Page = id,
                PetsCount = this.petsService.GetCount(),
                PetsPerPage = PetsPerPage,
                AllPets = this.petsService.GetAllFemaleDogs(id, PetsPerPage),
            };

            return this.View(allPetsViewModel);
        }

        [Authorize]
        public IActionResult AllMaleCats(int id = 1)
        {
            const int PetsPerPage = 10;

            var allPetsViewModel = new AllPetsListViewModel()
            {
                Page = id,
                PetsCount = this.petsService.GetCount(),
                PetsPerPage = PetsPerPage,
                AllPets = this.petsService.GetAllMaleCats(id, PetsPerPage),
            };

            return this.View(allPetsViewModel);
        }

        [Authorize]
        public IActionResult AllFemaleCats(int id = 1)
        {
            const int PetsPerPage = 10;

            var allPetsViewModel = new AllPetsListViewModel()
            {
                Page = id,
                PetsCount = this.petsService.GetCount(),
                PetsPerPage = PetsPerPage,
                AllPets = this.petsService.GetAllFemaleCats(id, PetsPerPage),
            };

            return this.View(allPetsViewModel);
        }

        [Authorize]
        public IActionResult ByCreationDateAscending(int id = 1)
        {
            const int PetsPerPage = 10;

            var allPetsViewModel = new AllPetsListViewModel()
            {
                Page = id,
                PetsCount = this.petsService.GetCount(),
                PetsPerPage = PetsPerPage,
                AllPets = this.petsService.GetAllPetsByCreationDateAscending(id, PetsPerPage),
            };

            return this.View(allPetsViewModel);
        }

        [Authorize]
        public IActionResult ByCreationDateDescending(int id = 1)
        {
            const int PetsPerPage = 10;

            var allPetsViewModel = new AllPetsListViewModel()
            {
                Page = id,
                PetsCount = this.petsService.GetCount(),
                PetsPerPage = PetsPerPage,
                AllPets = this.petsService.GetAllPetsByCreationDateDescending(id, PetsPerPage),
            };

            return this.View(allPetsViewModel);
        }

        [Authorize]
        public async Task<IActionResult> SendPetToEmail(int id)
        {
            var pet = this.petsService.GetById<PetViewModel>(id);

            var html = new StringBuilder();
            html.AppendLine($"<h1>{pet.Name}</h1>");
            html.AppendLine($"<h3>{pet.TypeOfPet}</h3>");
            html.AppendLine($"<h3>{pet.BreedName}</h3>");
            html.AppendLine($"<h3>{pet.Sex}</h3>");
            html.AppendLine($"<h3>Active from {pet.StartOfPeriod} until {pet.EndOfPeriod}</h3>");
            html.AppendLine($"<h3>Owned by {pet.OwnerUserName}</h3>");

            var user = await this.userManager.GetUserAsync(this.User);

            await this.emailSender.SendEmailAsync("faustwfs@gmail.com", "Beauty&ThePet", user.Email, pet.Name, html.ToString());

            return this.RedirectToAction(nameof(this.ViewPetInfo), new { id });
        }
    }
}

BeautyAndThePet/Web/BeautyAndThePet.Web/Views/Messages/New.cshtml
@model BeautyAndThePet.Web.ViewModels.Messages.MessageInputViewModel
@{
    ViewData["Title"] = "New message";
}

<h1 class="text-center">@ViewData["Title"]</h1>
<hr/>
<div class="col-md-6 offset-md-3 font h5">
    <h6>From: @Model.From</h6>
    <hr />
    <form method="post" id="editForm">
        <div asp-validation-summary="All" class="text-danger"></div>

        <h6>To: @Model.From</h6>
        <hr/>
        <div class="form-group">
            <label asp-for="Text"></label>
            <textarea asp-for="Text" class="form-control"></textarea>
            <span asp-validation-for="Text" class="text-danger"></span>
        </div>
        <input type="hidden" asp-for="Id" /><a asp-controller="Pets" asp-action="MyPets" class="btn btn-secondary">Back</a>
        <button type="submit" class="btn btn-warning">Send</button>
    </form>
</div>

BeautyAndThePet/Web/BeautyAndThePet.Web/Views/Messages/NewEmpty.cshtml
@model BeautyAndThePet.Web.ViewModels.Messages.MessageInputViewModel
@{
    ViewData["Title"] = "New message";
}

<h1 class="text-center">@ViewData["Title"]</h1>
<hr/>
<div class="col-md-6 offset-md-3 font h5">
    <h6>From: @Model.From</h6>
    <hr/>
    <form method="post" id="editForm">
        <div asp-validation-summary="All" class="text-danger"></div>
        <div class="form-group">
            <label asp-for="To"></label>
            <input asp-for="To" class="form-control" />
            <span asp-validation-for="To" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="Text"></label>
            <textarea asp-for="Text" class="form-control"></textarea>
            <span asp-validation-for="Text" class="text-danger"></span>
        </div>
        <hr />
        <input type="hidden" asp-for="Id" />
        <a asp-controller="Home" asp-action="Index" asp-route-id="@Model.Id" class="btn btn-secondary">Back</a>
        <button type="submit" class="btn btn-warning">Send</button>
    </form>
</div>

BeautyAndThePet/Web/BeautyAndThePet.Web/Views/Messages/ReadReceivedMessage.cshtml
@using BeautyAndThePet.Web.ViewModels.Messages
@model MessageViewModel
@{
    this.ViewData["Title"] = "View message";
}

<div>
    <p>@Model.From</p>
    <p>@Model.To</p>
    <p>@Model.Text</p>
    <p>@Model.SentOn</p>
</div>
<a class="btn btn-primary" asp-controller="Messages" asp-action="Received">Back</a>

BeautyAndThePet/Web/BeautyAndThePet.Web/Views/Messages/ReadSentMessage.cshtml
@using BeautyAndThePet.Web.ViewModels.Messages
@model MessageViewModel
@{
    this.ViewData["Title"] = "View message";
}

<div class="text-center">
    <p>From: @Model.From</p>
    <p>To: @Model.To</p>
    <p>Text: @Model.Text</p>
    <p>Sent on: @Model.SentOn</p>
</div>
    <a class="btn btn-primary" asp-controller="Messages" asp-action="Sent">Back</a>

BeautyAndThePet/Web/BeautyAndThePet.Web/Views/Messages/Received.cshtml
@using BeautyAndThePet.Web.ViewModels.Messages
@model MessagesListViewModel
@{
    if (Model.Messages.Any())
    {
        this.ViewData["Title"] = "Received messages";
    }
    else
    {
        this.ViewData["Title"] = "You have no received messages yet";
    }
}

@foreach (var message in Model.Messages)
{
    <div>
        <h1>@this.ViewData["Title"]</h1>
        <div>
            <p>@message.From</p>
            <p>@message.Text</p>
            <p>@message.SentOn</p>
        </div>
        <a class="btn btn-primary" asp-controller="Messages" asp-action="ReadReceivedMessage" asp-route-id="@message.Id">Read</a>
        <a class="btn btn-warning" asp-controller="Messages" asp-action="NewEmpty" asp-route-to="@message.From">Reply</a>
        <hr />
    </div>
}

BeautyAndThePet/Web/BeautyAndThePet.Web/Views/Messages/Sent.cshtml
@using BeautyAndThePet.Web.ViewModels.Messages
@model MessagesListViewModel
@{
    if (Model.Messages.Any())
    {
        this.ViewData["Title"] = "Sent messages";
    }
    else
    {
        this.ViewData["Title"] = "You have no sent messages yet";
    }
}

<h1 class="text-center">@this.ViewData["Title"]</h1>
@foreach (var message in Model.Messages)
{
    <div>
        <p>To: @message.To</p>
        <p>Text: @message.Text</p>
        <p>Sent on: @message.SentOn</p>
    </div>

    <a class="btn btn-primary" asp-controller="Messages" asp-action="ReadSentMessage" asp-route-id="@message.Id">View</a>
    <hr />
}

BeautyAndThePet/Web/BeautyAndThePet.Web/Views/Messages/Unread.cshtml
@using BeautyAndThePet.Web.ViewModels.Messages
@model MessagesListViewModel
@{
    if (Model.Messages.Any())
    {
        this.ViewData["Title"] = "Unread messages";
    }
    else
    {
        this.ViewData["Title"] = "You have no unread messages";
    }
}

@foreach (var message in Model.Messages)
{
    <div>
        <h1>@this.ViewData["Title"]</h1>
        <div>
            <p>@message.From</p>
            <p>@message.Text</p>
            <p>@message.SentOn</p>
        </div>
        <a class="btn btn-primary" asp-controller="Messages" asp-action="ReadReceivedMessage" asp-route-id="@message.Id">Read</a>
        <a class="btn btn-primary" asp-controller="Messages" asp-action="NewEmpty" asp-route-to="@message.From">Reply</a>
        <hr />
    </div>
}